# re: 'in-project = true'
# this will cause a '.venv' folder to be placed at the root of python projects
# instead of being kept remote location
# this makes directing tools (e.g. language servers) to the files simpler
# (otherwise the your IDE might complain that you're trying to use modules
#  that are not installed, for example)
# And the path will be consistent across users allowing hard coding in local
# configs or the myproject.toml file
# Example tool path configuration that might take advantage of this:
#
#   [tool.pyright]
#   exclude = [".venv"]
#   venvPath = "."
#   venv = ".venv"

[virtualenvs]
in-project = true
